name: Deploy Staging Theme

on:
  push:
    branches:
      - development

jobs:
  deploy:
    name: Deploy LIVE Staging Theme
    runs-on: ubuntu-latest
    steps:
      # basically git clone
      - uses: actions/checkout@v2
      # deploy shopify theme
      - uses: pgrimaud/action-shopify@2.1.3
        env:
          SHOPIFY_PASSWORD: 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
          SHOPIFY_STORE_URL: mous-dev.myshopify.com
          SHOPIFY_THEME_ID: 44895076425
          THEME_PATH: ./
        with:
          args: --ignored-file=config/settings_data.json --ignored-file=locales/*
